project:
  name: deoa
  regions:
    - us-east-1
tests:
  static:
    parameters:
      GitHubToken: '{{resolve:secretsmanager:github/personal-access-token:SecretString}}'
      SiteBucketName: delete-pmd-static-1533
    template: ./samples/static/pipeline.yml
  # ec2:
  #   parameters:
  #     EmailAddress: fake-email@fake-fake-fake-email.com
  #     KeyName: paul-duvall-demo-us-east-1	
  #   template: ./samples/ec2/pipeline.yml